import Footer from '@/components/shared/Footer'
import Header from '@/components/shared/Header'
import { AuthProvider } from '@/contexts/AuthContext'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin']
})

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin']
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
}

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en'>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <AuthProvider>
               <Header />
               {children}
               <Footer />

               {/* Toast Configuration - Anti-spam via Map-based tracking system */}
               <Toaster
                  position='top-right'
                  reverseOrder={false}
                  gutter={8}
                  toastOptions={{
                     // Default options
                     duration: 4000,
                     style: {
                        background: '#363636',
                        color: '#fff',
                        padding: '16px',
                        borderRadius: '8px',
                        fontSize: '14px',
                        fontWeight: '500',
                        maxWidth: '500px'
                     },
                     // Success
                     success: {
                        duration: 4000,
                        iconTheme: {
                           primary: '#10b981',
                           secondary: '#fff'
                        }
                     },
                     // Error
                     error: {
                        duration: 5000,
                        iconTheme: {
                           primary: '#ef4444',
                           secondary: '#fff'
                        }
                     },
                     // Loading
                     loading: {
                        iconTheme: {
                           primary: '#3b82f6',
                           secondary: '#fff'
                        }
                     }
                  }}
               />
            </AuthProvider>
         </body>
      </html>
   )
}
